"""Build the four ordered notebooks without external notebook dependencies."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
NOTEBOOKS = ROOT / "notebooks"


def markdown(source: str) -> dict:
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": source.strip().splitlines(keepends=True),
    }


def code(source: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source.strip().splitlines(keepends=True),
    }


def write_notebook(filename: str, cells: list[dict]) -> None:
    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "paper_env (Python 3.11)",
                "language": "python",
                "name": "paper_env",
            },
            "language_info": {"name": "python", "version": "3.11"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    path = NOTEBOOKS / filename
    path.write_text(json.dumps(notebook, indent=1), encoding="utf-8")


def main() -> None:
    NOTEBOOKS.mkdir(parents=True, exist_ok=True)

    write_notebook(
        "00_research_design.ipynb",
        [
            markdown(
                r"""
# Research Design

## Critical replication of *A Mean Convection Finite Difference Method for Solving Black Scholes Model for Option Pricing*

**Original author:** An Ning (2023)  
**Original paper:** [arXiv:2308.06808](https://arxiv.org/abs/2308.06808)  
**Replication type:** Independent computational replication and reproducibility audit
"""
            ),
            markdown(
                """
## Research question

Can finite-difference and Monte Carlo methods reproduce European option prices under the paper's stated Black-Scholes parameters, and are the reported accuracy claims reproducible from the methodological information provided?
"""
            ),
            markdown(
                """
## Planned comparisons

1. Recalculate the analytical Black-Scholes benchmark.
2. Implement explicit finite differences on a 100-by-1,000 grid.
3. Implement Crank-Nicolson on the same grid.
4. Run 100,000-path Monte Carlo simulations with fixed seeds.
5. Audit all four reported tables.
6. Study transparent convection multipliers around the standard value of one.
"""
            ),
            markdown(
                """
## Validation rules

- Measure independent numerical error against the standard analytical Black-Scholes formula.
- Use put-call parity and monotonicity tests.
- Record every grid, boundary, and random-seed assumption.
- Retain discrepancies rather than tuning the code to match reported values.
"""
            ),
            markdown(
                """
## Reproducibility limitation

The paper does not fully define its flux operators, the function used to construct the tuning parameter, the upper price boundary, code, or random seed. Therefore, this project does not claim an exact reconstruction of MCFDM. It provides a conventional-method replication plus a clearly labelled paper-inspired convection sensitivity analysis.
"""
            ),
            markdown(
                """
## Authorship and AI-use statement

AI assistance was used for coding support and debugging. The replication design, parameter checks, interpretation of outputs, documented assumptions, and final conclusions were reviewed by the replication author. All numerical claims are generated by reproducible code and tests in this repository.
"""
            ),
        ],
    )

    setup = r"""
from pathlib import Path
import sys

ROOT = Path.cwd()
if ROOT.name == "notebooks":
    ROOT = ROOT.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from src.option_pricing import black_scholes_price
from src.replication import build_paper_audit

print(f"Repository root: {ROOT}")
"""

    write_notebook(
        "01_black_scholes_benchmark.ipynb",
        [
            markdown(
                """
# 01 - Analytical Black-Scholes Benchmark

The analytical formula supplies the reference price used to evaluate every numerical method. This notebook also checks whether the paper's values follow from its stated parameters.
"""
            ),
            code(setup),
            markdown(
                r"""
## Baseline scenario

Table 1 states (S_0=5), (K=5.5), (r=5\%\), and (sigma=25\%\). Maturities are three months, six months, and one year.
"""
            ),
            code(
                """
S0, K, r, sigma = 5.0, 5.5, 0.05, 0.25
maturities = [0.25, 0.50, 1.00]
labels = ["3M", "6M", "1Y"]

baseline = pd.DataFrame({
    "maturity": labels,
    "standard_black_scholes": [
        black_scholes_price(S0, K, T, r, sigma, "call")
        for T in maturities
    ],
    "paper_reported_exact": [0.09737, 0.13606, 0.40131],
})
baseline["absolute_gap"] = abs(
    baseline["standard_black_scholes"] - baseline["paper_reported_exact"]
)
baseline.round(6)
"""
            ),
            code(
                """
ax = baseline.plot(
    x="maturity",
    y=["paper_reported_exact", "standard_black_scholes"],
    marker="o",
    figsize=(8, 4.5),
)
ax.set(title="Audit of Paper Table 1", xlabel="Maturity", ylabel="Call price")
ax.grid(alpha=0.3)
plt.show()
"""
            ),
            markdown(
                """
## Full four-table audit

For the two tables labelled as puts, both the standard call and put formula are calculated using the spot and strike stated in the paper's narrative. This allows the numerical values themselves to reveal which contract they resemble.
"""
            ),
            code(
                """
audit = build_paper_audit()
audit.round(6)
"""
            ),
            code(
                """
audit.groupby(["table", "closest_standard_formula"]).size().rename("rows")
"""
            ),
            markdown(
                """
## Interpretation

- The one-year values in all four tables are extremely close to standard call prices.
- The six-month values in the two call tables do not follow from the stated parameters.
- Every row of Tables 3 and 4 is closer to a call than a put, despite the put labels.

These are replication observations. They are retained rather than removed or fitted away.
"""
            ),
        ],
    )

    numerical_setup = r"""
from pathlib import Path
import sys

ROOT = Path.cwd()
if ROOT.name == "notebooks":
    ROOT = ROOT.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from src.option_pricing import (
    black_scholes_price,
    crank_nicolson_price,
    explicit_fdm_price,
    monte_carlo_price,
    scaled_convection_fdm_price,
)
"""

    write_notebook(
        "02_finite_difference_methods.ipynb",
        [
            markdown(
                """
# 02 - Finite-Difference and Monte Carlo Methods

At expiry the option payoff is known. A finite-difference method places option values on an asset-price/time grid and works backward to today. The analytical Black-Scholes value remains the validation target.
"""
            ),
            code(numerical_setup),
            code(
                """
S0, K, T, r, sigma = 5.0, 5.5, 0.25, 0.05, 0.25
M, N = 100, 1_000
exact = black_scholes_price(S0, K, T, r, sigma, "call")

explicit = explicit_fdm_price(S0, K, T, r, sigma, "call", M, N)
crank_nicolson = crank_nicolson_price(S0, K, T, r, sigma, "call", M, N)
monte_carlo = monte_carlo_price(
    S0, K, T, r, sigma, "call", simulations=100_000, seed=42
)

comparison = pd.DataFrame({
    "method": ["Analytical", "Explicit FDM", "Crank-Nicolson", "Monte Carlo"],
    "price": [exact, explicit.price, crank_nicolson.price, monte_carlo.price],
    "elapsed_seconds": [0.0, explicit.elapsed_seconds, crank_nicolson.elapsed_seconds, monte_carlo.elapsed_seconds],
})
comparison["absolute_error"] = abs(comparison["price"] - exact)
comparison.round(6)
"""
            ),
            markdown(
                """
## Reading the FDM output

The expiry payoff has a sharp corner at the strike. Before expiry, uncertainty gives the call positive time value even when the current asset price is below the strike. The PDE moves the payoff curve backward and smooths that corner.
"""
            ),
            code(
                """
asset_grid = explicit.asset_grid
terminal_payoff = np.maximum(asset_grid - K, 0.0)

plt.figure(figsize=(8, 4.5))
plt.plot(asset_grid, terminal_payoff, "--", label="Payoff at expiry")
plt.plot(asset_grid, explicit.value_grid, label="Explicit FDM value today")
plt.plot(asset_grid, crank_nicolson.value_grid, ":", label="Crank-Nicolson value today")
plt.axvline(K, color="red", linestyle="--", alpha=0.7, label=f"Strike K={K}")
plt.xlim(3, 9)
plt.ylim(0, 4)
plt.xlabel("Asset price")
plt.ylabel("Call value")
plt.title("Terminal Payoff and Numerical Values Today")
plt.grid(alpha=0.3)
plt.legend()
plt.show()
"""
            ),
            markdown(
                """
## Paper-inspired convection sensitivity

The paper proposes weakening or enhancing the convection term. Since its full tuning function is not reproducible from the text, the experiment below varies a transparent fixed multiplier. `theta=1` is the standard Black-Scholes convection term; values below or above one weaken or strengthen it.
"""
            ),
            code(
                """
sensitivity_rows = []
for theta in [0.75, 0.90, 1.00, 1.10, 1.25]:
    result = scaled_convection_fdm_price(
        S0, K, T, r, sigma, "call", M, N, theta=theta
    )
    sensitivity_rows.append({
        "theta": theta,
        "price": result.price,
        "absolute_error": abs(result.price - exact),
    })

sensitivity = pd.DataFrame(sensitivity_rows)
sensitivity.round(6)
"""
            ),
            code(
                """
ax = sensitivity.plot(
    x="theta", y="absolute_error", marker="o", legend=False, figsize=(8, 4.5)
)
ax.axvline(1.0, color="black", linestyle="--", label="Standard convection")
ax.set(title="Convection Multiplier Sensitivity", xlabel="Theta", ylabel="Absolute error")
ax.legend()
ax.grid(alpha=0.3)
plt.show()
"""
            ),
            markdown(
                """
## Numerical conclusion

For the baseline case, both independently implemented finite-difference methods closely match the analytical value. Monte Carlo is also close but retains sampling uncertainty. On this grid, changing the convection multiplier away from one does not improve the baseline error, so the paper's broad superiority claim is not established by this transparent sensitivity experiment.
"""
            ),
        ],
    )

    write_notebook(
        "03_replication_results.ipynb",
        [
            markdown(
                """
# 03 - Complete Replication Results

This notebook regenerates all CSV tables and figures from the reusable source code. Run it from top to bottom before committing a final version.
"""
            ),
            code(
                r"""
from pathlib import Path
import sys

ROOT = Path.cwd()
if ROOT.name == "notebooks":
    ROOT = ROOT.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import pandas as pd
from IPython.display import Image, display
from src.replication import run_full_replication

outputs = run_full_replication(ROOT / "results")
print("All tables and figures regenerated successfully.")
"""
            ),
            markdown("## Audit of the paper's reported exact values"),
            code("outputs[\"audit\"].round(6)"),
            markdown("## Independent and reported method comparison"),
            code("outputs[\"comparison\"].round(6)"),
            markdown("## Convection sensitivity"),
            code("outputs[\"sensitivity\"].round(6)"),
            code(
                """
for filename in [
    "paper_table1_audit.png",
    "independent_method_comparison.png",
    "independent_method_errors.png",
    "convection_sensitivity.png",
]:
    display(Image(filename=str(ROOT / "results" / "figures" / filename)))
"""
            ),
            markdown(
                """
## Final conclusions

1. Conventional explicit FDM and Crank-Nicolson reproduce the analytical Black-Scholes benchmark closely on the stated grid.
2. The paper's six-month exact call values cannot be reproduced from its stated parameters.
3. The tables labelled as puts numerically resemble calls under the narrative spot/strike settings.
4. Monte Carlo results vary with the random sample, so a seed, standard error, and confidence interval are required.
5. The reported MCFDM cannot be uniquely reconstructed because essential operators and tuning-function details are missing.

The strongest outcome is therefore a transparent critical replication: working numerical methods, quantified error, reproducible tests, and documented limits on what the source paper allows another researcher to reproduce.
"""
            ),
        ],
    )

    print(f"Built 4 notebooks in {NOTEBOOKS}")


if __name__ == "__main__":
    main()
